name: A workflow for my new action on PR's
on: pull_request
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ./action-b
      env:
        MY_NAME: "Luke"
